"""init

Revision ID: 1880fd8e263b
Revises: 1473c84efc91
Create Date: 2019-08-26 16:48:04.245456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1880fd8e263b'
down_revision = '1473c84efc91'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
