"""init

Revision ID: d97f6935bcf7
Revises: 52ed1da68e7e
Create Date: 2019-08-25 02:51:15.946195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97f6935bcf7'
down_revision = '52ed1da68e7e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
