"""init

Revision ID: 1f3a353e7170
Revises: 4e6f85f38d58
Create Date: 2019-08-27 01:06:04.978069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3a353e7170'
down_revision = '4e6f85f38d58'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_answer_request_id_request', 'answer', type_='foreignkey')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_answer_request_id_request', 'answer', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###
