"""init

Revision ID: a72b380bda4a
Revises: abbec99319a1
Create Date: 2019-08-27 12:20:40.459091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72b380bda4a'
down_revision = 'abbec99319a1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
