"""init

Revision ID: e2cb0eaabf46
Revises: cee496046173
Create Date: 2019-08-26 14:45:58.563977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cb0eaabf46'
down_revision = 'cee496046173'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
