"""init

Revision ID: c2ce87a64e23
Revises: 0e3cf709bef0
Create Date: 2019-08-25 00:01:25.792759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ce87a64e23'
down_revision = '0e3cf709bef0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
