"""init

Revision ID: 199da3dd90ec
Revises: f8800e88f9ba
Create Date: 2019-08-25 00:36:01.921756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199da3dd90ec'
down_revision = 'f8800e88f9ba'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
