"""init

Revision ID: f8800e88f9ba
Revises: 7edf3e4d679f
Create Date: 2019-08-25 00:30:44.878063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8800e88f9ba'
down_revision = '7edf3e4d679f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
