"""init

Revision ID: 7edf3e4d679f
Revises: 206591ac6b54
Create Date: 2019-08-25 00:17:54.856354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edf3e4d679f'
down_revision = '206591ac6b54'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
