"""init

Revision ID: 2253caefc178
Revises: 4b29e394b6f6
Create Date: 2019-08-26 15:51:24.731562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2253caefc178'
down_revision = '4b29e394b6f6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
