"""init

Revision ID: 1473c84efc91
Revises: 2253caefc178
Create Date: 2019-08-26 16:20:02.737694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1473c84efc91'
down_revision = '2253caefc178'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
