"""init

Revision ID: 206591ac6b54
Revises: c2ce87a64e23
Create Date: 2019-08-25 00:10:22.285221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206591ac6b54'
down_revision = 'c2ce87a64e23'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
