"""init

Revision ID: 672851386259
Revises: d97f6935bcf7
Create Date: 2019-08-25 12:38:57.457812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672851386259'
down_revision = 'd97f6935bcf7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
