"""init

Revision ID: 52ed1da68e7e
Revises: 199da3dd90ec
Create Date: 2019-08-25 00:47:41.264236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ed1da68e7e'
down_revision = '199da3dd90ec'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
