"""init

Revision ID: b3ae9fd2bf0e
Revises: d8625cd7a2ed
Create Date: 2019-08-27 01:57:10.606970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ae9fd2bf0e'
down_revision = 'd8625cd7a2ed'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('request_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'request_id')
    # ### end Alembic commands ###
