"""init

Revision ID: f2f075b4f877
Revises: 755d0d573ee6
Create Date: 2019-08-23 16:35:41.974961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f075b4f877'
down_revision = '755d0d573ee6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
