"""init

Revision ID: abbec99319a1
Revises: b3ae9fd2bf0e
Create Date: 2019-08-27 09:53:55.736080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbec99319a1'
down_revision = 'b3ae9fd2bf0e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_answer_request_id_request'), 'answer', 'request', ['request_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_answer_request_id_request'), 'answer', type_='foreignkey')
    # ### end Alembic commands ###
