"""init

Revision ID: 755d0d573ee6
Revises: 
Create Date: 2019-08-23 12:54:48.862495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755d0d573ee6'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request'))
    )
    op.create_table('answer',
    sa.Column('link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=255), nullable=True),
    sa.Column('question_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], name=op.f('fk_answer_request_id_request')),
    sa.PrimaryKeyConstraint('question_id', name=op.f('pk_answer'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('request')
    # ### end Alembic commands ###
