"""init

Revision ID: 0e3cf709bef0
Revises: f2f075b4f877
Create Date: 2019-08-23 16:37:33.608587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3cf709bef0'
down_revision = 'f2f075b4f877'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
