"""init

Revision ID: 36d870bb6db8
Revises: 672851386259
Create Date: 2019-08-25 21:55:29.169699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d870bb6db8'
down_revision = '672851386259'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
