"""init

Revision ID: 4e6f85f38d58
Revises: 76e9b3ab89f6
Create Date: 2019-08-27 00:41:36.873182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6f85f38d58'
down_revision = '76e9b3ab89f6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
